name: deploy to server

on : push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: hola Mundo
              run: echo "hola mundo"

    second_job:
        runs-on : ubuntu-latest
        steps:
            - name: Hola Mundo
              run: hola mundo segundo
                        
